name: deploy-prd

on:
  push:
    paths:
      - ".github/workflows/**"
      - "backend/src/**"
      - "backend/build.gradle"
      - "backend/settings.gradle"
      - "backend/Dockerfile.prd"
    branches:
      - main

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      branch: prd
      branch_upper: PRD
      doppler_config: prd
      tag_prefix: v-prd-
      dockerfile: Dockerfile.prd
      instance_env: prd
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TK_GITHUB_ACCESS_TOKEN: ${{ secrets.TK_GITHUB_ACCESS_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN_OWNER: ${{ secrets.TK_GITHUB_ACCESS_TOKEN_OWNER }}
      DOPPLER_SERVICE_TOKEN: ${{ secrets.DOPPLER_PRD_SERVICE_TOKEN }}
      BASTION_SSH_KEY: ${{secrets.BASTION_SSH_KEY}}