name: deploy-develop

on:
  push:
    paths:
      - ".github/workflows/**"
      - "backend/src/**"
      - "backend/build.gradle"
      - "backend/settings.gradle"
      - "backend/Dockerfile.dev"
    branches:
      - develop

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      branch: dev
      branch_upper: DEV
      doppler_config: dev
      tag_prefix: v-dev-
      dockerfile: Dockerfile.dev
      instance_env: dev
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TK_GITHUB_ACCESS_TOKEN: ${{ secrets.TK_GITHUB_ACCESS_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN_OWNER: ${{ secrets.TK_GITHUB_ACCESS_TOKEN_OWNER }}
      DOPPLER_SERVICE_TOKEN: ${{ secrets.DOPPLER_DEV_SERVICE_TOKEN }}
      BASTION_SSH_KEY: ${{secrets.BASTION_SSH_KEY}}
